steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['install', '.']
  env: ['PROJECT_ROOT=main']
- name: 'gcr.io/cloud-builders/go'
  args: ['test', 'main']
  env: ['PROJECT_ROOT=main']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/main', '.']
images: ['gcr.io/$PROJECT_ID/main']