steps:

- id: "Install"
  name: 'gcr.io/cloud-builders/go'
  args: ['install', '.']
  env: ['PROJECT_ROOT=app'] 

- id: "Rodando testes"  
  name: 'gcr.io/cloud-builders/go'
  args: ['test', 'app']
  env: ['PROJECT_ROOT=app'] 
  
- id: "Build e push"  
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/app', '.']
images: ['gcr.io/$PROJECT_ID/app']